USE master;
GO
ALTER DATABASE YOUR_DATABASE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE YOUR_DATABASE
COLLATE SQL_Latin1_General_CP1_CI_AI ; -- here your collation, in my case, this
GO
ALTER DATABASE YOUR_DATABASE SET MULTI_USER WITH ROLLBACK IMMEDIATE;
GO
